# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfbe5ab945a24c882f1e34218b77eae91c24d393551c3b73bc5a1f0ae18b3f31c6b2238928aabf39988368b4ab4a00d31576f19e47164d3c51f4f782dc341873

test:
  secret_key_base: 128c580c25b00549228a6a78ab868e4452cb56b546dc3e7b1623833a88e498a8a380c98fb8367bbd78d15eed1134de54238fc88f54baa5b45d3a2aa2220d9741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
